In [8]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.12.2-py3-none-any.whl (293 kB)
     -------------------------------------- 293.3/293.3 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\users\aqtak\miniconda3\lib\site-packages (from seaborn) (3.7.2)
Requirement already satisfied: pandas>=0.25 in c:\users\aqtak\miniconda3\lib\site-packages (from seaborn) (2.0.3)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\users\aqtak\miniconda3\lib\site-packages (from seaborn) (1.24.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aqtak\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.1.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\aqtak\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aqtak\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.41.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\aqtak\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.0.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aqtak\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.8.2)
Requirement already satisfied: cycler>=0.10 in c:\users\aqtak\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\aqtak\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\aqtak\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (23.0)
Requirement already satisfied: tzdata>=2022.1 in c:\users\aqtak\miniconda3\lib\site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\aqtak\miniconda3\lib\site-packages (from pandas>=0.25->seaborn) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\aqtak\miniconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.12.2
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [11]:
import pandas as pd
df = pd.read_csv('E:\LearnCode\Dicoding\imdb_indonesian_movies_2.csv')
df = df.drop(columns=['judul_film'])

In [12]:
df.head(5)

                                  ringkasan_sinopsis  genre
0  Raden Mas Said putra sulung Tumenggung Wilarik...  Drama
1  Soe Hok Gie adalah seorang aktivis yang hidup ...  Drama
2  Guru Bangsa Tjokroaminoto menceritakan tentang...  Drama
3  POL menceritakan kisah hidup yang luar biasa d...  Drama
4  Perjalanan pahlawan Indonesia KH Ahmad Dahlan ...  Drama

In [13]:
category = pd.get_dummies(df.genre)
df_baru = pd.concat([df, category], axis=1)
df_baru = df_baru.drop(columns='genre')
df_baru

,ringkasan_sinopsis,Drama,Horor,Komedi,Laga,Romantis
0,Raden Mas Said putra sulung Tumenggung Wilarik...,True,False,False,False,False
1,Soe Hok Gie adalah seorang aktivis yang hidup ...,True,False,False,False,False
2,Guru Bangsa Tjokroaminoto menceritakan tentang...,True,False,False,False,False
3,POL menceritakan kisah hidup yang luar biasa d...,True,False,False,False,False
4,Perjalanan pahlawan Indonesia KH Ahmad Dahlan ...,True,False,False,False,False
...,...,...,...,...,...,...
1000,Winter in Tokyo berpusat pada kehidupan Ishida...,False,False,False,False,True
1001,Markonah melarikan diri ke Jakarta karena akan...,False,False,False,False,True
1002,"Tempat aking lebih dari 36 jam, Last Night ada...",False,False,False,False,True
1003,Proyek baru ini adalah tentang seorang lelaki ...,False,False,False,False,True
1004,"Atika (Meriam Bellina) mantan penyanyi tenar, ...",False,False,False,False,True

In [14]:
sinopsis = df_baru['ringkasan_sinopsis'].values
label = df_baru[['Drama', 'Horor', 'Komedi', 'Laga', 'Romantis']].values

In [15]:
from sklearn.model_selection import train_test_split
sinopsis_latih, sinopsis_test, label_latih, label_test = train_test_split(sinopsis, label, test_size=0.2)

In [16]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
 
tokenizer = Tokenizer(num_words=5000, oov_token='x')
tokenizer.fit_on_texts(sinopsis_latih) 
tokenizer.fit_on_texts(sinopsis_test)
 
sekuens_latih = tokenizer.texts_to_sequences(sinopsis_latih)
sekuens_test = tokenizer.texts_to_sequences(sinopsis_test)
 
padded_latih = pad_sequences(sekuens_latih) 
padded_test = pad_sequences(sekuens_test)

In [17]:
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=5000, output_dim=16),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(5, activation='softmax')
])
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [18]:
num_epochs = 30
history = model.fit(padded_latih, label_latih, epochs=num_epochs, 
                    validation_data=(padded_test, label_test), verbose=2)

Epoch 1/30
26/26 - 7s - loss: 1.6103 - accuracy: 0.1828 - val_loss: 1.6123 - val_accuracy: 0.1940 - 7s/epoch - 285ms/step
Epoch 2/30
26/26 - 4s - loss: 1.6054 - accuracy: 0.2214 - val_loss: 1.6084 - val_accuracy: 0.2090 - 4s/epoch - 172ms/step
Epoch 3/30
26/26 - 4s - loss: 1.5603 - accuracy: 0.3134 - val_loss: 1.6067 - val_accuracy: 0.2637 - 4s/epoch - 171ms/step
Epoch 4/30
26/26 - 4s - loss: 1.3535 - accuracy: 0.3706 - val_loss: 1.7922 - val_accuracy: 0.2289 - 4s/epoch - 172ms/step
Epoch 5/30
26/26 - 4s - loss: 1.0360 - accuracy: 0.4664 - val_loss: 2.0506 - val_accuracy: 0.1891 - 4s/epoch - 171ms/step
Epoch 6/30
26/26 - 4s - loss: 0.8414 - accuracy: 0.5634 - val_loss: 2.9439 - val_accuracy: 0.2935 - 4s/epoch - 171ms/step
Epoch 7/30
26/26 - 5s - loss: 0.6060 - accuracy: 0.7463 - val_loss: 3.0361 - val_accuracy: 0.2687 - 5s/epoch - 174ms/step
Epoch 8/30
26/26 - 5s - loss: 0.3112 - accuracy: 0.9017 - val_loss: 4.2628 - val_accuracy: 0.2985 - 5s/epoch - 175ms/step
Epoch 9/30
26/26 - 5s - loss: 0.4009 - accuracy: 0.8843 - val_loss: 3.0127 - val_accuracy: 0.2438 - 5s/epoch - 174ms/step
Epoch 10/30
26/26 - 5s - loss: 0.1962 - accuracy: 0.9590 - val_loss: 4.0131 - val_accuracy: 0.2388 - 5s/epoch - 177ms/step
Epoch 11/30
26/26 - 5s - loss: 0.0721 - accuracy: 0.9888 - val_loss: 4.6572 - val_accuracy: 0.2736 - 5s/epoch - 177ms/step
Epoch 12/30
26/26 - 4s - loss: 0.0246 - accuracy: 0.9975 - val_loss: 5.7788 - val_accuracy: 0.2786 - 4s/epoch - 172ms/step
Epoch 13/30
26/26 - 4s - loss: 0.0105 - accuracy: 1.0000 - val_loss: 6.3876 - val_accuracy: 0.2886 - 4s/epoch - 170ms/step
Epoch 14/30
26/26 - 4s - loss: 0.0084 - accuracy: 0.9988 - val_loss: 6.2857 - val_accuracy: 0.2736 - 4s/epoch - 170ms/step
Epoch 15/30
26/26 - 4s - loss: 0.0089 - accuracy: 0.9988 - val_loss: 7.2180 - val_accuracy: 0.2736 - 4s/epoch - 169ms/step
Epoch 16/30
26/26 - 4s - loss: 0.0034 - accuracy: 1.0000 - val_loss: 7.3444 - val_accuracy: 0.2736 - 4s/epoch - 172ms/step
Epoch 17/30
26/26 - 4s - loss: 0.0026 - accuracy: 1.0000 - val_loss: 7.6860 - val_accuracy: 0.2786 - 4s/epoch - 171ms/step
Epoch 18/30
26/26 - 4s - loss: 0.0021 - accuracy: 1.0000 - val_loss: 7.8962 - val_accuracy: 0.2587 - 4s/epoch - 171ms/step
Epoch 19/30
26/26 - 4s - loss: 0.0018 - accuracy: 1.0000 - val_loss: 7.9200 - val_accuracy: 0.2687 - 4s/epoch - 171ms/step
Epoch 20/30
26/26 - 4s - loss: 0.0015 - accuracy: 1.0000 - val_loss: 8.1166 - val_accuracy: 0.2637 - 4s/epoch - 171ms/step
Epoch 21/30
26/26 - 4s - loss: 0.0012 - accuracy: 1.0000 - val_loss: 8.3344 - val_accuracy: 0.2587 - 4s/epoch - 171ms/step
Epoch 22/30
26/26 - 5s - loss: 0.0010 - accuracy: 1.0000 - val_loss: 8.5041 - val_accuracy: 0.2637 - 5s/epoch - 173ms/step
Epoch 23/30
26/26 - 4s - loss: 8.8015e-04 - accuracy: 1.0000 - val_loss: 8.6448 - val_accuracy: 0.2637 - 4s/epoch - 173ms/step
Epoch 24/30
26/26 - 4s - loss: 7.5897e-04 - accuracy: 1.0000 - val_loss: 8.7886 - val_accuracy: 0.2687 - 4s/epoch - 170ms/step
Epoch 25/30
26/26 - 4s - loss: 6.8980e-04 - accuracy: 1.0000 - val_loss: 8.8383 - val_accuracy: 0.2637 - 4s/epoch - 172ms/step
Epoch 26/30
26/26 - 4s - loss: 6.4092e-04 - accuracy: 1.0000 - val_loss: 8.9263 - val_accuracy: 0.2537 - 4s/epoch - 171ms/step
Epoch 27/30
26/26 - 4s - loss: 5.7062e-04 - accuracy: 1.0000 - val_loss: 9.1341 - val_accuracy: 0.2537 - 4s/epoch - 171ms/step
Epoch 28/30
26/26 - 4s - loss: 4.8224e-04 - accuracy: 1.0000 - val_loss: 9.3498 - val_accuracy: 0.2736 - 4s/epoch - 170ms/step
Epoch 29/30
26/26 - 4s - loss: 4.3521e-04 - accuracy: 1.0000 - val_loss: 9.4019 - val_accuracy: 0.2736 - 4s/epoch - 170ms/step
Epoch 30/30
26/26 - 4s - loss: 4.0017e-04 - accuracy: 1.0000 - val_loss: 9.4622 - val_accuracy: 0.2687 - 4s/epoch - 170ms/step